### ISSUE TITLE
Forgot password web view logo

### ISSUE THREAD

**Issue by axldyb** [schibsted/account-sdk-ios#137]
I tested the forgot password flow for the IdentityUI and discovered that I was taken to a web view with an old version of the FINN.no logo. The path here is `/flow/password`. When testing on the web I found that the path is different `/forgotpassword/{some code}` and the logo is the correct one. How can I get the correct logo? 

#### Old logo in SchibstedAccount SDK vs. new logo found on the web

<img width="300" alt="image" src="https://user-images.githubusercontent.com/1060670/40973275-f52ad9ae-68c3-11e8-865a-b14fdd5678c7.png"> <img width="300" alt="image" src="https://user-images.githubusercontent.com/1060670/40973276-f76e8bca-68c3-11e8-97f3-53275e5e034c.png">

**Comment by axldyb** [comment]
Also, on the SDK version has a link that says "Back to FINN.no (iPad)". First of all, why have that there when there is a "Done"-button. Second, where does the iPad part comes from?

**Comment by aliak00** [comment]
So the web flows use a different backend the the mobile SDKs. So I think that's why the web goes to a different url. I'll have to check with the webflow peeps as to why the logo is not correct though. I'm guessing it has to be set somewhere by someone but I have no idea where or who.

And ya, agree with the webview issue, it has been brought up before as well. See https://jira.schibsted.io/browse/ID-2403

And "FINN.no (iPad)" is the name of your client in selfservice and probably comes from there.

**Comment by aliak00** [comment]
Ait, checked. And yeah the logo is set by you guys on self service. Your web client and mobile client have different images set so you need to go in to selfservice and fix.

Closing this for now. Shout if it needs to be reopened.

**Comment by axldyb** [comment]
Thanks for the clarification!

**Comment by axldyb** [comment]
Also, the web view seems to be in English even though my app and the other native screens in the SDK is in Norwegian @aliak00.

**Comment by aliak00** [comment]
No probs. Language is also in self service.
