### ISSUE TITLE
webSessionURL() API does not work properly if redirectURL contains "%20"

### ISSUE THREAD

**Issue by salling** [schibsted/account-sdk-ios#172]
We authenticate with redirect URL:

2018-07-06 15:21:56.792235+0200 FVN[25075:26411303] [🔷 Debug] [SPIDAuthenticator.swift:55] authenticateURLIfPossible(_:backendConfiguration:logger:completion:) > Successfully retrieved session URL for "https://www.krsby.no/tag/pharrell%20williams": https://payment.schibsted.no/session/914bf7189d63afff9850bd0e9b65e16acc6030db75218c923e06da599c45402e

But when loading the resulting URL in a web view, it fails:
<img width="515" alt="screen shot 2018-07-06 at 15 22 03" src="https://user-images.githubusercontent.com/1453580/42381108-6f43e0c6-8130-11e8-8fa4-39268fa13a6d.png">

We are pretty sure it's the "%20" (percent-encoding) that's triggering the problem, because other URLs with %20 fail, but those without work fine.

**Comment by aliak00** [comment]
Are you passing in the URL as an already percent encoded URL? Because the redirect URI in for webSessionURL url-form encodes everything before sending it out. So if you have a %20 inside what is assumed to be an unencoded string, it will get encoded to %2520 (percent sign gets encoded). So I'm assuming there's some kind of mechanic happening with what we think you want access to and what your setup in client service has.

What is the value for the redirectURI in self service?

**Comment by aliak00** [comment]
Marking as invalid with the given info. Comment if there's more.
