### ISSUE TITLE
Send headers identifying the SDK and version

### ISSUE THREAD

**Issue by ksimons** [schibsted/account-sdk-ios#30]
The headers should be:

`SDK-Type: ios`
`SDK-Version: <version here>`

These should be sent on the request to the Schibsted account APIs (not on authenticated requests to the clients' servers).

Ok to still send the custom user agent, but because the JS SDK can't set a custom user agent, we'll use the headers everywhere.

**Comment by aliak00** [comment]
Few questions before we these in stone:

1. SDK-Type: should that be "platform" ? This is going to be "android", or "iOS", or "web" right? Or?
2. I think we should be a bit more explicit and make the prefix Schibsted-Account-SDK instead of just SDK, reason being that it is not unlikely that there will be other "sdk"s contacting spid as well, and the dashes seem like common HTTP header word separation practices (also because we also have X-Schibsted-Account-User-Agent)

**Comment by aliak00** [comment]
meh update: the headers are what spid already expects. so will just put those in.
